import {
  LayoutDashboard,
  BookOpen,
  Users,
  GraduationCap,
  Building2,
  ClipboardList,
  CalendarDays,
  ClipboardCheck,
  BarChart3,
  Settings,
  FileText,
  RefreshCcw,
  BookMarked,
  UserCog,
  Layers,
  Megaphone,
  Award,
} from "lucide-react";

export const directorNav = [
  { label: "Dashboard", href: "/director", icon: "LayoutDashboard" },
  { label: "Announcements", href: "/director/announcements", icon: "Megaphone" },
  { label: "Rank Sheet & CGPA", href: "/director/ranksheet", icon: "Award" },
  {
    label: "Academic Management",
    href: "/director/academics",
    icon: "BookOpen",
    children: [
      { label: "Courses", href: "/director/courses", icon: "BookMarked" },
      { label: "Syllabus", href: "/director/academics/syllabus", icon: "FileText" },
      { label: "Curriculum", href: "/director/academics/curriculum", icon: "Layers" },
    ],
  },
  {
    label: "Faculty Management",
    href: "/director/faculty",
    icon: "Users",
  },
  {
    label: "Student Management",
    href: "/director/students",
    icon: "GraduationCap",
  },
  {
    label: "HOD / Department",
    href: "/director/departments",
    icon: "Building2",
  },
  { label: "Examinations", href: "/director/examinations", icon: "ClipboardList" },
  { label: "Timetable", href: "/timetable", icon: "CalendarDays" },
  { label: "Attendance", href: "/director/attendance", icon: "ClipboardCheck" },
  { label: "Reports & Analytics", href: "/director/reports", icon: "BarChart3" },
  { label: "Master Setup", href: "/director/master-setup", icon: "UserCog" },
  { label: "Settings", href: "/director/settings", icon: "Settings" },
];

export const hodNav = [
  { label: "Dashboard", href: "/hod", icon: "LayoutDashboard" },
  { label: "Faculty Management", href: "/hod/faculty", icon: "Users" },
  { label: "Faculty Workload", href: "/hod/workload", icon: "UserCog" },
  { label: "Student Directory", href: "/hod/students", icon: "GraduationCap" },
  { label: "CR Assignment", href: "/hod/cr-assignment", icon: "Award" },
  { label: "Department Subjects", href: "/hod/subjects", icon: "BookOpen" },
  { label: "Master Syllabus", href: "/hod/syllabus", icon: "FileText" },
  { label: "Curriculum & Credits", href: "/hod/curriculum", icon: "Layers" },
  { label: "Dept Timetable", href: "/hod/timetable", icon: "CalendarDays" },
  { label: "Academic Year", href: "/hod/master-setup", icon: "RefreshCcw" },
  { label: "Attendance Oversight", href: "/hod/attendance", icon: "ClipboardCheck" },
  { label: "Study Materials", href: "/hod/resources", icon: "BookMarked" },
  { label: "Assignments Oversight", href: "/hod/assignments", icon: "ClipboardList" },
  { label: "Rank Sheet & CGPA", href: "/hod/ranksheet", icon: "Award" },
  { label: "Announcements", href: "/hod/announcements", icon: "Megaphone" },
];

export const facultyNav = [
  { label: "Dashboard", href: "/faculty", icon: "LayoutDashboard" },
  { label: "My Subjects", href: "/faculty/subjects", icon: "BookOpen" },
  { label: "Attendance", href: "/faculty/attendance", icon: "ClipboardCheck" },
  { label: "My Students", href: "/faculty/students", icon: "GraduationCap" },
  { label: "Study Materials", href: "/faculty/resources", icon: "FileText" },
  { label: "Assignments", href: "/faculty/assignments", icon: "ClipboardList" },
  { label: "Announcements", href: "/faculty/announcements", icon: "Megaphone" },
  { label: "Timetable", href: "/faculty/timetable", icon: "CalendarDays" },
  { label: "Results & Marks", href: "/faculty/results", icon: "BarChart3" },
  { label: "Rank Sheet & CGPA", href: "/faculty/ranksheet", icon: "Award" },
  { label: "Faculty Profile", href: "/faculty/profile", icon: "UserCog" },
];

export const studentNav = [
  { label: "Dashboard", href: "/student", icon: "LayoutDashboard" },
  { label: "My Subjects", href: "/student/subjects", icon: "BookOpen" },
  { label: "Timetable", href: "/student/timetable", icon: "CalendarDays" },
  { label: "Attendance", href: "/student/attendance", icon: "ClipboardCheck" },
  { label: "Assignments", href: "/student/assignments", icon: "ClipboardList" },
  { label: "Results", href: "/student/results", icon: "FileText" },
  { label: "Resources", href: "/student/resources", icon: "Layers" },
  { label: "Settings", href: "/student/settings", icon: "Settings" },
];

export const iconMap: Record<string, React.ElementType> = {
  LayoutDashboard,
  BookOpen,
  Users,
  GraduationCap,
  Building2,
  ClipboardList,
  CalendarDays,
  ClipboardCheck,
  BarChart3,
  Settings,
  FileText,
  RefreshCcw,
  BookMarked,
  UserCog,
  Layers,
  Megaphone,
  Award,
};
